In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

In [2]:
#Reading files:
users = pd.read_csv('user_data.csv', encoding='latin-1')
problems = pd.read_csv('problem_data.csv', encoding='latin-1')
attempts = pd.read_csv('train_submissions.csv', encoding='latin-1')
test = pd.read_csv('test_submissions.csv', encoding='latin-1')

In [3]:
#print(users)
#print(users.shape)
#user.head()

In [4]:
#print(problems.shape)
#problems.head()

In [5]:
#print(attempts.shape)
#attempts.head()

In [6]:
#print(test.shape)

In [7]:
n_users_attempted = attempts.user_id.unique().shape[0]
n_problems_attempted = attempts.problem_id.unique().shape[0]
#print(n_users)
#print(n_items)

In [8]:
empt=[]
for i in attempts.user_id:
    temp=int(i.split('_')[1]) 
    empt.append(temp)
attempts.user_id=empt
empt=[]
for i in attempts.problem_id:
    temp=int(i.split('_')[1]) 
    empt.append(temp)
attempts.problem_id=empt
unique_users_attempted=attempts.user_id.unique().tolist()
unique_problems_attempted=attempts.problem_id.unique().tolist()
data_matrix = np.ones((n_users_attempted, n_problems_attempted))
data_matrix=(-1)*data_matrix                                             #-1 means problem not attempted
for line in attempts.itertuples():
     data_matrix[unique_users_attempted.index(line[1]),unique_problems_attempted.index(line[2])] = line[3]
print(data_matrix)

[[ 1. -1.  4. ... -1. -1. -1.]
 [-1.  3.  1. ... -1. -1. -1.]
 [-1. -1.  1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]]


In [9]:
tag=[]
unique_tags=[]
empt=[]
for f in problems.tags:
    if type(f)!=float:
        tag=f.split(',')
        for i in tag:
            if i not in unique_tags:
                unique_tags.append(i)
        empt.append(tag)                                   #to convert it to list
    else:
        empt.append(f)
        if f not in unique_tags:
            unique_tags.append(f)
print unique_tags
problems.tags=empt

[nan, u'greedy', u'implementation', u'constructive algorithms', u'math', u'brute force', u'dfs and similar', u'dsu', u'graphs', u'number theory', u'dp', u'data structures', u'expression parsing', u'bitmasks', u'divide and conquer', u'sortings', u'shortest paths', u'combinatorics', u'strings', u'games', u'hashing', u'binary search', u'two pointers', u'trees', u'probabilities', u'ternary search', u'flows', u'meet-in-the-middle', u'*special', u'geometry', u'graph matchings', u'string suffix structures', u'fft', u'matrices', u'schedules', u'2-sat', u'chinese remainder theorem']


In [10]:
n_problems = problems.problem_id.unique().shape[0]

#create problem profile
empt=[]
for j in problems.level_type:
    if type(j)!=float:
        empt.append(ord(j)-ord('A')+1)
    else:
        empt.append(0)
problems.level_type=empt
empt=[]
for i in problems.problem_id:
    temp=int(i.split('_')[1]) 
    empt.append(temp)
problems.problem_id=empt
problem_profile = np.zeros((n_problems, len(unique_tags)+2))
for c in problems.itertuples():
    index=problems.problem_id.tolist().index(c[1])
    problem_profile[index,0]= c[2]
    problem_profile[index,1]= c[3]
    if type(c[4])!=list:
        problem_profile[index,unique_tags.index(c[4])+2]=1
    else:
        for i in c[4]:
            problem_profile[index,unique_tags.index(i)+2]=1    
            
print problem_profile

[[8.0e+00     nan 1.0e+00 ... 0.0e+00 0.0e+00 0.0e+00]
 [1.0e+00     nan 1.0e+00 ... 0.0e+00 0.0e+00 0.0e+00]
 [6.0e+00     nan 1.0e+00 ... 0.0e+00 0.0e+00 0.0e+00]
 ...
 [3.0e+00 1.5e+03 0.0e+00 ... 0.0e+00 0.0e+00 0.0e+00]
 [1.0e+00 5.0e+02 0.0e+00 ... 0.0e+00 0.0e+00 0.0e+00]
 [2.0e+00     nan 1.0e+00 ... 0.0e+00 0.0e+00 0.0e+00]]


In [85]:
#create user profile
#we need to create the user profile matrix as having boolean values for each entry of the problem tag and the mean rating for that too
users = pd.read_csv('user_data.csv', encoding='latin-1')
empt=[]
for i in users.user_id:
    temp=int(i.split('_')[1]) 
    empt.append(temp)
users.user_id=empt
user_profile = np.zeros((n_problems, len(unique_tags)+2))
for c in users.itertuples():
    index=users.user_id.tolist().index(c[1])
    mean=0
    no=0
    problem=np.zeros((len(unique_tags),len(unique_problems_attempted)))
    i=0
    for attempt in data_matrix.tolist()[unique_users_attempted.index(c[1])]:
        i+=1
        if attempt!=-1:
            mean+=attempt
            no+=1
            p=problems.problem_id.tolist().index(unique_problems_attempted[i])
            
            #if type(c[4])!=list:
            #    problem_profile[index,unique_tags.index(c[4])+2]=1
            #else:
            #    for j in c[4]:
            #        problem_profile[index,unique_tags.index(i)+2]=1
            #problem[,i]+=attempt
            
    #mean=

ValueError: 3177 is not in list